import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const work_Sans = Work_Sans({ subsets: ["latin"],weight: '400', });

export const metadata = {
  
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${work_Sans.className} `}>

        <Header />

        {children}

        <Footer />

        </body>
        
    </html>
  );
}
